### ISSUE TITLE
There is no npm dcs-mission-parser

### ISSUE THREAD

**Issue by Dragonius** [Ked57/dcs-mission-parser#1]
npm install dcs-mission-parser
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/dcs-mission-parser - Not found
npm ERR! 404
npm ERR! 404  'dcs-mission-parser@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-01T17_05_59_273Z-debug-0.log

**Comment by Ked57** [comment]
Hi sorry I don't think I ever published this it had a lot a of problems with putting it all back together. I should archive this repo
